export const FETCH_PATIENTS_START = 'FETCH_PATIENTS_START';
export const FETCH_PATIENTS_SUCCESS = 'FETCH_PATIENTS_SUCCESS';
export const FETCH_PATIENTS_FAIL = 'FETCH_PATIENTS_FAIL';
export const CHOSE_PATIENT = 'CHOSE_PATIENT';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const LOAD_START = 'LOAD_START';
export const LOAD_SUCCESS = 'LOAD_SUCCESS';
export const LOAD_FAIL = 'LOAD_FAIL';
export const DELETE_FILE_SUCCESS = 'DELETE_FILE_SUCCESS';
export const LOAD_FILE_DATA_SUCCESS = 'LOAD_FILE_DATA_SUCCESS';
export const FETCH_FILE_START = 'FETCH_FILE_START';
export const FETCH_FILE_SUCCESS = 'FETCH_FILE_SUCCESS';
export const FETCH_FILE_FAIL = 'FETCH_FILE_FAIL';